# MongoDB Connection
spring.data.mongodb.uri=mongodb://localhost:27017/behaviourbridgedb
spring.data.mongodb.database=behaviourbridgedb

# Server
server.port=8080

# JWT
jwt.secret=BehaviourBridgeTracksSecretKey2024SuperLongSecretKeyForSecurity
jwt.expiration=86400000

# Logging
logging.level.org.springframework.data.mongodb=DEBUG
logging.level.com.behaviourbridgetracks=DEBUG

#Properties
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs